# Page Info
title: Advanced Deep Learning
description: Advanced Deep Learning course webpage, containing materials, exercises and lectures for the course.
url: https://afspies.github.io

# Styling
theme: just-the-docs
color_scheme: dark

# Navigation
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
